### ISSUE TITLE
Crashes on ArchLinux

### ISSUE THREAD

**Issue by keiosweb** [virtual-programming/saintsrow2-linux#12]
Hello,

I start the game, I see first two short animations (with sound), then the game crashes. I sent the report, it's under keyword LSESENTCPU, I'm also putting it here: http://kopy.io/VPIgK

I wanted to ask if you need some more information maybe?

**Comment by David-UPCT** [comment]
I also use archlinux and the game works for me (lots of issues, but no crashes). keiosweb, I can't see your link, it redirects me to an empty text page http://kopy.io/ .

**Comment by keiosweb** [comment]
ah sorry. https://gist.github.com/keiosweb/199bb669a37beeefd7e578c7dc0fa254 here it is again.

**Comment by keiosweb** [comment]
Fixed by creating .asoundrc with following details (card 0 is nvidia hdmi)

```
pcm.!default {
    type hw
    card 1
}

ctl.!default {
    type hw
    card 1
}

pcm.dmixer {
    type dmix
    ipc_key 1024
    ipc_key_add_uid 0
    ipc_perm 0660
}
pcm.dsp {
    type plug
    slave.pcm "dmix"
}
```
